(string_char) @string
(identifier) @constructor
(number) @number
(comment) @comment
(assign) @operator
(obrace) @punctuation.bracket
(cbrace) @punctuation.bracket
(opar) @punctuation.bracket
(cpar) @punctuation.bracket
(vbar) @operator
(comma) @punctuation.delimiter
